name: Build website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install graphviz libgraphviz-dev pkg-config
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build pages
      shell: bash
      run: |
        [ -d public ] || mkdir ./public
        for i in ./pages/*.yaml; do
          out="$(basename "$i" .yaml)"
          echo "Building $i to $out"
          python build.py "public/${out}" < "$i" > "public/${out}.html"
        done
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        enable_jekyll: true
